-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 17:30:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tfc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tfc` ;

-- -----------------------------------------------------
-- Schema tfc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tfc` DEFAULT CHARACTER SET utf8 ;
USE `tfc` ;

-- -----------------------------------------------------
-- Table `tfc`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tfc`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `tfc`.`USUARIOS` (
  `NUM_USUARIO` INT(7) ZEROFILL NOT NULL AUTO_INCREMENT,
  `NOMBRE_USUARIO` VARCHAR(20) NOT NULL,
  `PS_USUARIO` VARCHAR(16) NOT NULL,
  `DNI_USUARIO` VARCHAR(9) NOT NULL,
  `TLFN_USUARIO` VARCHAR(12) NOT NULL,
  `CORREO_USUARIO` VARCHAR(50) NOT NULL,
  `FECHA_ALTA_USUARIO` DATE NOT NULL,
  PRIMARY KEY (`NUM_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfc`.`BUTACAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tfc`.`BUTACAS` ;

CREATE TABLE IF NOT EXISTS `tfc`.`BUTACAS` (
  `ID_BUTACA` VARCHAR(7) NOT NULL COMMENT 'LATERAL BAJA = LC\nALTA LATERAL = AL\nLATERAL CUBIERTA = LC_0000\nFONDO SUR = FS_0000\nGRADA PREFERENCIA = GP_0000\nTRIBUNA CENTRAL = TC_0000\nPALCO CENTRAL = PC_0000\nPALCO DE HONOR = PH_0000\nTRIBUNA ALTA PREFERENCIA =  AP_0000',
  `ZONA_BUTACA` VARCHAR(30) NOT NULL,
  `PUERTA_BUTACA` VARCHAR(1) NOT NULL,
  `PRECIO_BUTACA` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`ID_BUTACA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfc`.`PARTIDOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tfc`.`PARTIDOS` ;

CREATE TABLE IF NOT EXISTS `tfc`.`PARTIDOS` (
  `ID_PARTIDO` VARCHAR(10) NOT NULL,
  `FECHA_HORA_PARTIDO` DATETIME NOT NULL,
  `EQUIPO_LOCAL` VARCHAR(50) NOT NULL,
  `EQUIPO_VISITANTE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_PARTIDO`, `FECHA_HORA_PARTIDO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tfc`.`USUARIOS`
-- -----------------------------------------------------
START TRANSACTION;
USE `tfc`;
INSERT INTO `tfc`.`USUARIOS` (`NUM_USUARIO`, `NOMBRE_USUARIO`, `PS_USUARIO`, `DNI_USUARIO`, `TLFN_USUARIO`, `CORREO_USUARIO`, `FECHA_ALTA_USUARIO`) VALUES (DEFAULT, 'Quique', 'Pruebas1234', '54210769E', '+34675167636', 'quique.monre@gmail.com', '2025-04-23');

COMMIT;


-- -----------------------------------------------------
-- Data for table `tfc`.`PARTIDOS`
-- -----------------------------------------------------
START TRANSACTION;
USE `tfc`;
INSERT INTO `tfc`.`PARTIDOS` (`ID_PARTIDO`, `FECHA_HORA_PARTIDO`, `EQUIPO_LOCAL`, `EQUIPO_VISITANTE`) VALUES ('24/25-J-34', '2025-07-2 21:00', 'RAYO VALLECANO', 'GETAFE');
INSERT INTO `tfc`.`PARTIDOS` (`ID_PARTIDO`, `FECHA_HORA_PARTIDO`, `EQUIPO_LOCAL`, `EQUIPO_VISITANTE`) VALUES ('24/25-J-36', '2025-07-14 21:00', 'RAYO VALLECANO', 'BETIS');
INSERT INTO `tfc`.`PARTIDOS` (`ID_PARTIDO`, `FECHA_HORA_PARTIDO`, `EQUIPO_LOCAL`, `EQUIPO_VISITANTE`) VALUES ('24/25-J-38', '2025-07-25 21:30', 'RAYO VALLECANO', 'MALLORCA');

COMMIT;

