<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>butacas</title>
</head>
<body>
<?php
error_reporting (E_ALL);
require("conexion.php");
$bd=conectar();
$butacas=$bd->prepare("SELECT ID_BUTACA, ZONA_BUTACA, PUERTA_BUTACA, PRECIO_BUTACA FROM BUTACAS");
$butacas->execute(array());
//contadores de las butacas (importante para el codigo)
$ALTA_LATERAL=1;
$LATERAL_CUBIERTA=1;
$LATERAL_BAJA=1;
$FONDO_SUR=1;
$GRADA_PREFERENCIA=1;
$TRIBUNA_CENTRAL=1;
$PALCO_HONOR=1;
$PALCO_CENTRAL=1;
$TRIBUNA_ALTA_PREFERENCIA=1;
//precios por localización
$precio_AL= 29.99;
$precio_LC= 39.99;
$precio_LB= 24.99;
$precio_FS= 19.99;
$precio_GP= 29.99;
$precio_TC= 44.99;
$precio_PH= 99.99;
$precio_PC= 99.99;
$precio_AP= 34.99;
//bucles para añadir las butacas
for($ALTA_LATERAL ; $ALTA_LATERAL<1407; $ALTA_LATERAL++){
    if($ALTA_LATERAL<131){
        if($ALTA_LATERAL<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES('AL_000".$ALTA_LATERAL."',' TRIBUNA ALTA LATERAL', 'A', '".$precio_AL."');";
        }else if($ALTA_LATERAL>9 && $ALTA_LATERAL<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES( 'AL_00".$ALTA_LATERAL."', 'TRIBUNA ALTA LATERAL', 'A', '".$precio_AL."');";
        }else if($ALTA_LATERAL>99 && $ALTA_LATERAL<131){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES(  'AL_0".$ALTA_LATERAL."', 'TRIBUNA ALTA LATERAL', 'A', '".$precio_AL."');";
        }}else if($ALTA_LATERAL>130 && $ALTA_LATERAL<587){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES(  'AL_0".$ALTA_LATERAL."', 'TRIBUNA ALTA LATERAL', 'B', '".$precio_AL."');";
        }else if($ALTA_LATERAL>586 && $ALTA_LATERAL<1177){if($ALTA_LATERAL>586 && $ALTA_LATERAL<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES(  'AL_0".$ALTA_LATERAL."', 'TRIBUNA ALTA LATERAL', 'C', '".$precio_AL."');";
        }else if($ALTA_LATERAL>999 && $ALTA_LATERAL<1177){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES(   'AL_".$ALTA_LATERAL."', 'TRIBUNA ALTA LATERAL', 'C', '".$precio_AL."');";
        }}else if($ALTA_LATERAL>1176){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES(    'AL_".$ALTA_LATERAL."', 'TRIBUNA ALTA LATERAL', 'D', '".$precio_AL."');";
        }$butaca_AL=$bd->query($sql);
}
for($LATERAL_CUBIERTA ; $LATERAL_CUBIERTA<1407; $LATERAL_CUBIERTA++){
    if($LATERAL_CUBIERTA<131){
        if($LATERAL_CUBIERTA<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('LC_000".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'E', '".$precio_LC."');";
        }else if($LATERAL_CUBIERTA>9 && $LATERAL_CUBIERTA<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'LC_00".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'E', '".$precio_LC."');";
        }else if($LATERAL_CUBIERTA>99 && $LATERAL_CUBIERTA<131){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'LC_0".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'E', '".$precio_LC."');";
        }}else if($LATERAL_CUBIERTA>130 && $LATERAL_CUBIERTA<587){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'LC_0".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'F', '".$precio_LC."');";
        }else if($LATERAL_CUBIERTA>586 && $LATERAL_CUBIERTA<1177){if($LATERAL_CUBIERTA>586 && $LATERAL_CUBIERTA<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'LC_0".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'G', '".$precio_LC."');";
        }else if($LATERAL_CUBIERTA>999 && $LATERAL_CUBIERTA<1177){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'LC_".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'G', '".$precio_LC."');";
        }}else if($LATERAL_CUBIERTA>1176){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'LC_".$LATERAL_CUBIERTA."', 'TRIBUNA LATERAL CUBIERTA', 'H', '".$precio_LC."');";
        }$butaca_LC=$bd->query($sql);
}
for($LATERAL_BAJA ; $LATERAL_BAJA<1407; $LATERAL_BAJA++){
    if($LATERAL_BAJA<131){
        if($LATERAL_BAJA<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('LB_000".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'I', '".$precio_LB."');";
        }else if($LATERAL_BAJA>9 && $LATERAL_BAJA<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'LB_00".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'I', '".$precio_LB."');";
        }else if($LATERAL_BAJA>99 && $LATERAL_BAJA<131){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'LB_0".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'I', '".$precio_LB."');";
        }}else if($LATERAL_BAJA>130 && $LATERAL_BAJA<587){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'LB_0".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'J', '".$precio_LB."');";
        }else if($LATERAL_BAJA>586 && $LATERAL_BAJA<1177){if($LATERAL_BAJA<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'LB_0".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'K', '".$precio_LB."');";
        }else if($LATERAL_BAJA>999 && $LATERAL_BAJA<1177){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'LB_".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'K', '".$precio_LB."');";
        }}else if($LATERAL_BAJA>1176){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'LB_".$LATERAL_BAJA."', 'TRIBUNA LATERAL BAJA', 'L', '".$precio_LB."');";
        }$butaca_LB=$bd->query($sql);
}
for($FONDO_SUR ; $FONDO_SUR<899; $FONDO_SUR++){
    if($FONDO_SUR<210){
        if($FONDO_SUR<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('FS_000".$FONDO_SUR."', 'FONDO SUR', 'M', '".$precio_FS."');";
        }else if($FONDO_SUR>9 && $FONDO_SUR<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'FS_00".$FONDO_SUR."', 'FONDO SUR', 'M', '".$precio_FS."');";
        }else if($FONDO_SUR>99){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'FS_0".$FONDO_SUR."', 'FONDO SUR', 'M', '".$precio_FS."');";
        }}else if($FONDO_SUR>209 && $FONDO_SUR<450){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'FS_0".$FONDO_SUR."', 'FONDO SUR', 'N', '".$precio_FS."');";
        }else if($FONDO_SUR>449 && $FONDO_SUR<690){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'FS_0".$FONDO_SUR."', 'FONDO SUR', 'N', '".$precio_FS."');";
        }else if($FONDO_SUR>689){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'FS_".$FONDO_SUR."', 'FONDO SUR', 'O', '".$precio_FS."');";
        }$butaca_FS=$bd->query($sql);
}
for($GRADA_PREFERENCIA ; $GRADA_PREFERENCIA<1407; $GRADA_PREFERENCIA++){
    if($GRADA_PREFERENCIA<131){
        if($GRADA_PREFERENCIA<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('GP_000".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'P', '".$precio_GP."');";
        }else if($GRADA_PREFERENCIA>9 && $GRADA_PREFERENCIA<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'GP_00".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'P', '".$precio_GP."');";
        }else if($GRADA_PREFERENCIA>99 && $GRADA_PREFERENCIA<131){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'GP_0".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'P', '".$precio_GP."');";
        }}else if($GRADA_PREFERENCIA>130 && $GRADA_PREFERENCIA<587){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'GP_0".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'Q', '".$precio_GP."');";
        }else if($GRADA_PREFERENCIA>586 && $GRADA_PREFERENCIA<1177){if($GRADA_PREFERENCIA>586 && $GRADA_PREFERENCIA<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'GP_0".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'R', '".$precio_GP."');";
        }else if($GRADA_PREFERENCIA>999 && $GRADA_PREFERENCIA<1177){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'GP_".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'R', '".$precio_GP."');";
        }}else if($GRADA_PREFERENCIA>1176){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'GP_".$GRADA_PREFERENCIA."', 'GRADA DE PREFERENCIA', 'S', '".$precio_GP."');";
        }$butaca_GP=$bd->query($sql);
}
for($TRIBUNA_CENTRAL ; $TRIBUNA_CENTRAL<1152; $TRIBUNA_CENTRAL++){
    if($TRIBUNA_CENTRAL<577){
        if($TRIBUNA_CENTRAL<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('TC_000".$TRIBUNA_CENTRAL."', 'TRIBUNA CENTRAL', 'T', '".$precio_TC."');";
        }else if($TRIBUNA_CENTRAL>9 && $TRIBUNA_CENTRAL<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'TC_00".$TRIBUNA_CENTRAL."', 'TRIBUNA CENTRAL', 'T', '".$precio_TC."');";
        }else if($TRIBUNA_CENTRAL>99 && $TRIBUNA_CENTRAL<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'TC_0".$TRIBUNA_CENTRAL."', 'TRIBUNA CENTRAL', 'T', '".$precio_TC."');";
        }}else if($TRIBUNA_CENTRAL>576){if($TRIBUNA_CENTRAL<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'TC_0".$TRIBUNA_CENTRAL."', 'TRIBUNA CENTRAL', 'V', '".$precio_TC."');";
        }else if($TRIBUNA_CENTRAL>999){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'TC_".$TRIBUNA_CENTRAL."', 'TRIBUNA CENTRAL', 'V', '".$precio_TC."');";
        }}$butaca_TC=$bd->query($sql);
}
for($PALCO_HONOR ; $PALCO_HONOR<71; $PALCO_HONOR++){
    if($PALCO_HONOR<71){
        if($PALCO_HONOR<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('PH_000".$PALCO_HONOR."', 'PALCO DE HONOR', 'U', '".$precio_PH."');";
        }else if($PALCO_HONOR>9 && $PALCO_HONOR<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'PH_00".$PALCO_HONOR."', 'PALCO DE HONOR', 'U', '".$precio_PH."');";
        }
    }$butaca_GP=$bd->query($sql);
}
for($PALCO_CENTRAL ; $PALCO_CENTRAL<145; $PALCO_CENTRAL++){
    if($PALCO_CENTRAL<145){
        if($PALCO_CENTRAL<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('PC_000".$PALCO_CENTRAL."', 'PALCO_CENTRAL', 'U', '".$precio_PC."');";
        }else if($PALCO_CENTRAL>9 && $PALCO_CENTRAL<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'PC_00".$PALCO_CENTRAL."', 'PALCO_CENTRAL', 'U', '".$precio_PC."');";
        }else if($PALCO_CENTRAL>99){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'PC_0".$PALCO_CENTRAL."', 'PALCO_CENTRAL', 'U', '".$precio_PC."');";
        }}$butaca_PC=$bd->query($sql);
}
for($TRIBUNA_ALTA_PREFERENCIA ; $TRIBUNA_ALTA_PREFERENCIA<1407; $TRIBUNA_ALTA_PREFERENCIA++){
    if($TRIBUNA_ALTA_PREFERENCIA<131){
        if($TRIBUNA_ALTA_PREFERENCIA<10){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ('AP_000".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'W', '".$precio_AP."');";
        }else if($TRIBUNA_ALTA_PREFERENCIA>9 && $TRIBUNA_ALTA_PREFERENCIA<100){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES ( 'AP_00".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'W', '".$precio_AP."');";
        }else if($TRIBUNA_ALTA_PREFERENCIA>99 && $TRIBUNA_ALTA_PREFERENCIA<131){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'AP_0".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'W', '".$precio_AP."');";
        }}else if($TRIBUNA_ALTA_PREFERENCIA>130 && $TRIBUNA_ALTA_PREFERENCIA<587){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'AP_0".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'X', '".$precio_AP."');";
        }else if($TRIBUNA_ALTA_PREFERENCIA>586 && $TRIBUNA_ALTA_PREFERENCIA<1177){if($TRIBUNA_ALTA_PREFERENCIA>586 && $TRIBUNA_ALTA_PREFERENCIA<1000){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (  'AP_0".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'Y', '".$precio_AP."');";
        }else if($TRIBUNA_ALTA_PREFERENCIA>999 && $TRIBUNA_ALTA_PREFERENCIA<1177){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'AP_".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'Y', '".$precio_AP."');";
        }}else if($TRIBUNA_ALTA_PREFERENCIA>1176){
        $sql="INSERT INTO `tfc`.`BUTACAS`(`ID_BUTACA`, `ZONA_BUTACA`, `PUERTA_BUTACA`, `PRECIO_BUTACA`) VALUES (   'AP_".$TRIBUNA_ALTA_PREFERENCIA."', 'TRIBUNA ALTA PREFERENCIA', 'Z', '".$precio_AP."');";
        }$butaca_AP=$bd->query($sql);
    }
echo "<hr>";
$contador=$bd->query("SELECT * FROM BUTACAS");
$a=$contador->rowCount();
echo $a;
?>
</body>
</html>